const root = "platform-v2/ml-vs01/";

export const P02_M16_B_ALLOWLIST = [
  "BUILD_STATE.md",
  "CHANGED_FILES.md",
  "package.json",
  "scripts/verify-changed-files.ts",
  "scripts/verify-foundation-closeout.ts",
  "src/operational-pilot/replay-contract.ts",
  "src/operational-pilot/fixture-scenario.ts",
  "tests/operational-pilot-contracts.test.ts",
  "tests/operational-pilot-golden-path.test.ts",
  "scripts/p02-m16-b-changed-files.ts",
  "scripts/run-business-replay-harness.ts",
  "scripts/verify-business-replay-harness.ts",
  "src/business-replay/contracts.ts",
  "src/business-replay/scenario.ts",
  "src/business-replay/evidence.ts",
  "src/business-replay/classification.ts",
  "src/business-replay/coverage.ts",
  "src/business-replay/deterministic-ids.ts",
  "src/business-replay/platform-adapter.ts",
  "src/business-replay/runner.ts",
  "src/business-replay/report.ts",
  "src/business-replay/sanitization.ts",
  "src/business-replay/synthetic-scenarios.ts",
  "src/business-replay/index.ts",
  "src/business-replay/README.md",
  "tests/business-replay-contracts.test.ts",
  "tests/business-replay-classification.test.ts",
  "tests/business-replay-coverage.test.ts",
  "tests/business-replay-sanitization.test.ts",
  "tests/business-replay-runner.test.ts",
  "tests/business-replay-platform-adapter.test.ts",
  "tests/business-replay-report.test.ts",
  "tests/business-replay-determinism.test.ts",
  "tests/foundation-fixtures.test.ts",
  "scripts/verify-runtime.ts",
  "scripts/verify-no-placeholders.ts",
  "src/operational-pilot/contracts.ts",
  "src/operational-pilot/database.ts",
  "src/operational-pilot/observability.ts",
  "tests/scheduling-appointment-foundation.test.ts",
  "tests/returned-editor-review-final-source-foundation.test.ts",
  "tests/publication-delivery-entitlement-foundation.test.ts",
  "scripts/verify-catalog-administration-lifecycle-schema.ts",
  "scripts/verify-current-catalog-price-reconstruction-schema.ts",
  "scripts/verify-disposable-delivery-surface-local-fixture.ts",
  "scripts/verify-operational-pilot-golden-path.ts",
  "scripts/verify-order-foundation-schema.ts",
  "scripts/verify-property-hub-foundation-schema.ts",
  "scripts/verify-provider-neutral-file-backed-delivery.ts",
  "scripts/verify-scheduling-appointment-foundation-schema.ts",
].map((entry) => `${root}${entry}`);

if (P02_M16_B_ALLOWLIST.length !== 50 || new Set(P02_M16_B_ALLOWLIST).size !== 50) {
  throw new Error("P02-M16-B amended allowlist must contain exactly 50 unique paths");
}

