const root = "platform-v2/ml-vs01/";

export const P02_M16_E_ALLOWLIST = [
  "BUILD_STATE.md",
  "CHANGED_FILES.md",
  "package.json",
  "db/migrate.ts",
  "db/migrations/0023_runtime_intake_reconciliation_commands.sql",
  "scripts/p02-m16-e-changed-files.ts",
  "scripts/run-current-era-intake-reproof.ts",
  "scripts/verify-current-era-intake-reproof.ts",
  "scripts/verify-runtime-intake-reconciliation-commands.ts",
  "scripts/verify-changed-files.ts",
  "scripts/verify-foundation-closeout.ts",
  "src/current-shadow/contracts.ts",
  "src/current-shadow/database.ts",
  "src/current-shadow/index.ts",
  "src/current-shadow/privacy.ts",
  "src/current-shadow/source.ts",
  "src/runtime-intake/contracts.ts",
  "src/runtime-intake/index.ts",
  "tests/runtime-intake-reconciliation.test.ts",
  "tests/current-era-intake-reproof.test.ts",
  "tests/capture-session-ingest-custody-foundation.test.ts",
  "tests/catalog-administration-lifecycle.test.ts",
  "tests/current-catalog-price-reconstruction.test.ts",
  "tests/durable-media-operations-reconciliation-foundation.test.ts",
  "tests/editor-handoff-returned-media-intake-foundation.test.ts",
  "tests/job-service-workstream-foundation.test.ts",
  "tests/media-asset-identity-lineage-foundation.test.ts",
  "tests/media-cull-workspace-selected-media-foundation.test.ts",
  "tests/mission-plan-foundation.test.ts",
  "tests/order-foundation.test.ts",
  "tests/organization-records-dashboard-audited-export-foundation.test.ts",
  "tests/property-hub-foundation.test.ts",
  "tests/property-snapshot-schema.test.ts",
  "tests/provider-neutral-file-backed-delivery.test.ts",
  "tests/publication-delivery-entitlement-foundation.test.ts",
  "tests/returned-editor-review-final-source-foundation.test.ts",
  "tests/scheduling-appointment-foundation.test.ts",
  "tests/temporary-download-center-access-credential-gateway-foundation.test.ts",
  "tests/temporary-download-center-external-sharing-foundation.test.ts",
  "tests/migration-engine.test.ts",
  "tests/identity-tenancy-schema.test.ts",
  "tests/person-contacts-account-lifecycle-schema.test.ts",
  "tests/test-database-reset.test.ts",
  "scripts/verify-business-replay-harness.ts",
  "scripts/verify-capture-session-ingest-custody-schema.ts",
  "scripts/verify-catalog-administration-lifecycle-schema.ts",
  "scripts/verify-current-catalog-price-reconstruction-schema.ts",
  "scripts/verify-durable-media-operations-reconciliation-schema.ts",
  "scripts/verify-editor-handoff-returned-media-intake-schema.ts",
  "scripts/verify-historical-business-replay.ts",
  "scripts/verify-job-service-workstream-foundation-schema.ts",
  "scripts/verify-media-asset-identity-lineage-schema.ts",
  "scripts/verify-media-cull-workspace-selected-media-schema.ts",
  "scripts/verify-mission-plan-foundation-schema.ts",
  "scripts/verify-current-era-shadow.ts",
  "scripts/verify-operational-pilot-golden-path.ts",
  "scripts/verify-migration-engine.ts",
  "scripts/verify-order-foundation-schema.ts",
  "scripts/verify-person-contacts-account-lifecycle-schema.ts",
  "scripts/verify-property-hub-foundation-schema.ts",
  "scripts/verify-property-snapshot-schema.ts",
  "scripts/verify-scheduling-appointment-foundation-schema.ts",
  "scripts/verify-disposable-delivery-surface-local-fixture.ts",
  "scripts/verify-provider-neutral-file-backed-delivery.ts",
  "scripts/verify-organization-records-dashboard-audited-export.ts",
  "scripts/verify-publication-delivery-entitlement-schema.ts",
  "scripts/verify-returned-editor-review-final-source-schema.ts",
  "scripts/verify-temporary-download-center-access-credential-gateway-schema.ts",
  "scripts/verify-temporary-download-center-external-sharing-schema.ts",
].map((entry) => `${root}${entry}`);

if (P02_M16_E_ALLOWLIST.length !== 69 || new Set(P02_M16_E_ALLOWLIST).size !== 69) {
  throw new Error("P02-M16-E reconciled maximum allowlist must contain exactly 69 unique paths");
}
