import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import crypto from 'crypto';
import pg from 'pg';
import { resetTestDatabase } from '../db/reset-test-database.js';
import { IDENTITY_FIXTURES, ORGANIZATION_FIXTURE } from '../db/fixtures/identity-tenancy-fixtures.js';
import { ORDER_FOUNDATION_ORDER_ID, ORDER_ITEM_FIXTURES } from '../db/fixtures/order-foundation-fixtures.js';
import { PROPERTY_HUB_ID } from '../db/fixtures/property-hub-foundation-fixtures.js';

const TEST_DB='medialab_p02m16a_test'; const OWNER='medialab_p02m16a_test_owner';
const RUNTIME='medialab_p02m16a_test_app'; const SOCKET='/tmp/mlvs01-p02m16a-pg'; const PORT=55447;
const ACTOR=IDENTITY_FIXTURES[1].id; const SOURCE='SYNTHETIC_P02_M13_A_TEST';
const digest=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');

describe('P02-M13-A returned-editor review and final-source decision foundation',()=>{
  let owner:pg.Client;let runtime:pg.Client;
  const reset=()=>resetTestDatabase({host:SOCKET,port:PORT,database:TEST_DB,user:OWNER,runtimeUser:RUNTIME,confirm:TEST_DB});
  async function fail(p:Promise<unknown>,re?:RegExp){try{await p;throw new Error('Expected failure');}catch(e:any){if(e.message==='Expected failure')throw e;if(re)expect(e.message).toMatch(re);}}
  async function session(){const t=crypto.randomBytes(32).toString('base64url');await owner.query(`INSERT INTO medialab_core.development_sessions(id,identity_id,token_sha256,issued_at,expires_at) VALUES($1,$2,$3,clock_timestamp()-interval '1 minute',clock_timestamp()+interval '1 hour')`,[crypto.randomUUID(),ACTOR,digest(t)]);return t;}
  async function job(t:string){const j=await runtime.query<{create_job:string}>('SELECT medialab_core.create_job($1,$2,$3,$4,$5,$6)',[t,`job-${crypto.randomUUID()}`,ORGANIZATION_FIXTURE.id,ORDER_FOUNDATION_ORDER_ID,PROPERTY_HUB_ID,SOURCE]);const w=await runtime.query<{create_service_workstream:string}>('SELECT medialab_core.create_service_workstream($1,$2,$3,$4,$5)',[t,`ws-${crypto.randomUUID()}`,j.rows[0].create_job,ORDER_ITEM_FIXTURES[0].id,SOURCE]);return{jobId:j.rows[0].create_job,workstreamId:w.rows[0].create_service_workstream};}
  async function asset(t:string,j:{jobId:string;workstreamId:string}){const a=await runtime.query<{create_media_asset:string}>('SELECT medialab_core.create_media_asset($1,$2,$3,$4,$5::jsonb)',[t,`asset-${crypto.randomUUID()}`,j.jobId,j.workstreamId,JSON.stringify({source:SOURCE})]);const v=await runtime.query<{add_media_asset_version:string}>('SELECT medialab_core.add_media_asset_version($1,$2,$3,$4,$5,$6,$7,$8,$9)',[t,`ver-${crypto.randomUUID()}`,a.rows[0].create_media_asset,'ORIGINAL','source.dng',1000,'image/dng',digest(crypto.randomUUID()),SOURCE]);return{assetId:a.rows[0].create_media_asset,originalId:v.rows[0].add_media_asset_version};}
  async function handoffWithReturns(t:string,j:{jobId:string;workstreamId:string},count=2){
    const cw=await runtime.query<{create_cull_workspace:string}>('SELECT medialab_core.create_cull_workspace($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[t,`cull-${crypto.randomUUID()}`,j.jobId,j.workstreamId,'PHOTO','Photo cull','Synthetic cull',JSON.stringify({source:SOURCE})]);
    const originals:{assetId:string;originalId:string}[]=[];const candidates:string[]=[];
    for(let n=0;n<count;n++){const x=await asset(t,j);originals.push(x);const c=await runtime.query<{admit_cull_candidate:string}>('SELECT medialab_core.admit_cull_candidate($1,$2,$3,$4,$5,$6::uuid[],$7::jsonb)',[t,`admit-${crypto.randomUUID()}`,cw.rows[0].create_cull_workspace,x.assetId,x.originalId,[],JSON.stringify({source:SOURCE})]);candidates.push(c.rows[0].admit_cull_candidate);}
    await runtime.query('SELECT medialab_core.seal_cull_inventory($1,$2,$3,$4)',[t,`seal-${crypto.randomUUID()}`,cw.rows[0].create_cull_workspace,'Synthetic seal']);
    for(let n=0;n<candidates.length;n++)await runtime.query('SELECT medialab_core.decide_cull_candidate($1,$2,$3,$4,$5,$6,$7::uuid,$8::jsonb)',[t,`keep-${crypto.randomUUID()}`,candidates[n],'KEEP','Synthetic keep',n,null,JSON.stringify({source:SOURCE})]);
    await runtime.query('SELECT medialab_core.finalize_cull_workspace($1,$2,$3,$4,$5,$6,$7)',[t,`complete-cull-${crypto.randomUUID()}`,cw.rows[0].create_cull_workspace,'Synthetic completion',count,false,null]);
    const h=await runtime.query<{create_editor_handoff_batch:string}>('SELECT medialab_core.create_editor_handoff_batch($1,$2,$3,$4,$5,$6,$7::jsonb)',[t,`handoff-${crypto.randomUUID()}`,cw.rows[0].create_cull_workspace,'EXTERNAL_EDITOR','SYNTHETIC_EDITOR','Synthetic handoff',JSON.stringify({source:SOURCE})]);
    await runtime.query('SELECT medialab_core.record_editor_handoff_event($1,$2,$3,$4,$5,$6,$7::jsonb)',[t,`dispatch-${crypto.randomUUID()}`,h.rows[0].create_editor_handoff_batch,'DISPATCHED',0,'Synthetic dispatch',JSON.stringify({source:SOURCE})]);
    await runtime.query('SELECT medialab_core.record_editor_handoff_event($1,$2,$3,$4,$5,$6,$7::jsonb)',[t,`ack-${crypto.randomUUID()}`,h.rows[0].create_editor_handoff_batch,'ACKNOWLEDGED',1,'Synthetic acknowledgement',JSON.stringify({source:SOURCE})]);
    const intake=await runtime.query<{create_returned_media_intake_batch:string}>('SELECT medialab_core.create_returned_media_intake_batch($1,$2,$3,$4,$5,$6::jsonb)',[t,`intake-${crypto.randomUUID()}`,h.rows[0].create_editor_handoff_batch,'SYNTHETIC_RETURN','Synthetic intake',JSON.stringify({source:SOURCE})]);
    const hi=await owner.query('SELECT id,media_asset_id FROM medialab_core.editor_handoff_items WHERE handoff_batch_id=$1 ORDER BY ordinal',[h.rows[0].create_editor_handoff_batch]);const versions:string[]=[];
    for(let n=0;n<hi.rows.length;n++){const r=await runtime.query<{record_returned_media_item:string}>('SELECT medialab_core.record_returned_media_item($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::uuid,$11,$12,$13::jsonb)',[t,`return-${crypto.randomUUID()}`,intake.rows[0].create_returned_media_intake_batch,`edit-${n}.jpg`,1500,'image/jpeg',digest(`returned-${crypto.randomUUID()}`),'EXACT_MATCH','MANIFEST_REFERENCE',hi.rows[n].id,n,'Synthetic exact return',JSON.stringify({source:SOURCE})]);const c=await owner.query('SELECT returned_media_asset_version_id FROM medialab_core.returned_media_item_current WHERE returned_item_id=$1',[r.rows[0].record_returned_media_item]);versions.push(c.rows[0].returned_media_asset_version_id);}
    return{handoffId:h.rows[0].create_editor_handoff_batch,handoffItems:hi.rows,versions,originals,intakeId:intake.rows[0].create_returned_media_intake_batch};
  }
  async function review(t:string,handoffId:string,versions:string[],cycle=1){const b=await runtime.query<{create_returned_review_batch:string}>('SELECT medialab_core.create_returned_review_batch($1,$2,$3,$4,$5,$6::jsonb)',[t,`review-${crypto.randomUUID()}`,handoffId,cycle,'Synthetic review cycle',JSON.stringify({source:SOURCE})]);const items:string[]=[];for(let n=0;n<versions.length;n++){const i=await runtime.query<{admit_returned_review_item:string}>('SELECT medialab_core.admit_returned_review_item($1,$2,$3,$4,$5,$6::jsonb)',[t,`review-item-${crypto.randomUUID()}`,b.rows[0].create_returned_review_batch,versions[n],n,JSON.stringify({source:SOURCE})]);items.push(i.rows[0].admit_returned_review_item);}await runtime.query('SELECT medialab_core.seal_returned_review_inventory($1,$2,$3,$4,$5)',[t,`seal-review-${crypto.randomUUID()}`,b.rows[0].create_returned_review_batch,versions.length,'Synthetic review seal']);return{batchId:b.rows[0].create_returned_review_batch,items};}
  async function decide(t:string,item:string,disp:string,gen=0,instructions:string|null=null,key=`decision-${crypto.randomUUID()}`){return runtime.query<{record_returned_review_decision:string}>('SELECT medialab_core.record_returned_review_decision($1,$2,$3,$4,$5,$6,$7)',[t,key,item,disp,`Synthetic ${disp} decision`,instructions,gen]);}

  beforeAll(async()=>{await reset();owner=new pg.Client({host:SOCKET,port:PORT,database:TEST_DB,user:OWNER});runtime=new pg.Client({host:SOCKET,port:PORT,database:TEST_DB,user:RUNTIME});await owner.connect();await runtime.connect();});beforeEach(reset);afterAll(async()=>{await runtime.end();await owner.end();await reset();});

  it('replays 0016 with permission-only fixtures and exact restricted authority',async()=>{const l=await owner.query('SELECT filename FROM medialab_meta.schema_migrations ORDER BY filename');expect(l.rows).toHaveLength(27);expect(l.rows[22].filename).toBe('0023_runtime_intake_reconciliation_commands.sql');expect(l.rows[15].filename).toBe('0016_returned_editor_review_final_source_decision_foundation.sql');expect((await owner.query("SELECT code FROM medialab_core.permissions WHERE code LIKE 'media_return_review.%' ORDER BY code")).rows.map(r=>r.code)).toEqual(['media_return_review.manage','media_return_review.read']);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.returned_review_batches')).rows[0].n).toBe(0);const f=await owner.query(`SELECT p.proname,has_function_privilege($1,p.oid,'EXECUTE') runtime,has_function_privilege('public',p.oid,'EXECUTE') public FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='medialab_core' AND p.proname LIKE '%returned_review%' ORDER BY p.proname`,[RUNTIME]);expect(f.rows.filter(r=>r.runtime).map(r=>r.proname)).toEqual(['admit_returned_review_item','complete_returned_review_batch','create_returned_review_batch','get_returned_review_batch','get_returned_review_history','get_returned_review_lineage','link_returned_review_successor','list_returned_review_batches','record_returned_review_decision','seal_returned_review_inventory','supersede_returned_review_decision']);expect(f.rows.some(r=>r.public)).toBe(false);});

  it('ACCEPT and USE_ORIGINAL establish exact 0011 final sources with append-only supersession',async()=>{const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,2),rv=await review(t,x.handoffId,x.versions);await decide(t,rv.items[0],'ACCEPT');await decide(t,rv.items[1],'USE_ORIGINAL');let d=await owner.query(`SELECT r.disposition,s.version_id,s.designation FROM medialab_core.returned_review_decisions r JOIN medialab_core.media_approved_source_designations s ON s.id=r.final_source_designation_id ORDER BY r.decided_at,r.id`);expect(d.rows.map(r=>r.disposition).sort()).toEqual(['ACCEPT','USE_ORIGINAL']);expect(d.rows.find(r=>r.disposition==='ACCEPT').version_id).toBe(x.versions[0]);const expectedOriginal=(await owner.query(`SELECT v.id FROM medialab_core.returned_review_items i JOIN medialab_core.media_asset_versions v ON v.asset_id=i.media_asset_id AND v.version_kind='ORIGINAL' WHERE i.id=$1`,[rv.items[1]])).rows[0].id;expect(d.rows.find(r=>r.disposition==='USE_ORIGINAL').version_id).toBe(expectedOriginal);const current=(await owner.query('SELECT current_decision_id FROM medialab_core.returned_review_item_current WHERE review_item_id=$1',[rv.items[0]])).rows[0].current_decision_id;await runtime.query('SELECT medialab_core.supersede_returned_review_decision($1,$2,$3,$4,$5,$6,$7,$8)',[t,`correct-${crypto.randomUUID()}`,rv.items[0],current,'USE_ORIGINAL','Synthetic correction to original',null,1]);d=await owner.query('SELECT id,disposition,supersedes_decision_id FROM medialab_core.returned_review_decisions WHERE review_item_id=$1 ORDER BY decided_at,id',[rv.items[0]]);expect(d.rows).toHaveLength(2);expect(d.rows[1].supersedes_decision_id).toBe(d.rows[0].id);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_approved_source_designations')).rows[0].n).toBe(3);});

  it('keeps REJECT_REVISION item-level while unrelated accepted source remains valid and cycle completes',async()=>{const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,2),rv=await review(t,x.handoffId,x.versions);await decide(t,rv.items[0],'ACCEPT');await decide(t,rv.items[1],'REJECT_REVISION',0,'Reduce glare without changing crop');const c=(await owner.query('SELECT * FROM medialab_core.returned_review_batch_current WHERE review_batch_id=$1',[rv.batchId])).rows[0];expect(c).toMatchObject({resolved_count:2,final_source_count:1,revision_routed_count:1,unresolved_count:0});await runtime.query('SELECT medialab_core.complete_returned_review_batch($1,$2,$3,$4,$5)',[t,`complete-${crypto.randomUUID()}`,rv.batchId,3,'Synthetic review completion']);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.returned_revision_requests')).rows[0].n).toBe(1);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_approved_source_designations')).rows[0].n).toBe(1);expect((await owner.query('SELECT current_state FROM medialab_core.returned_review_batch_current WHERE review_batch_id=$1',[rv.batchId])).rows[0].current_state).toBe('COMPLETED');});

  it('QUICK_EDIT preserves exact source, requires immutable lineage and later human re-review before final',async()=>{const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,1),r1=await review(t,x.handoffId,x.versions);await decide(t,r1.items[0],'QUICK_EDIT',0,'Correct exposure only');await runtime.query('SELECT medialab_core.complete_returned_review_batch($1,$2,$3,$4,$5)',[t,`complete-${crypto.randomUUID()}`,r1.batchId,2,'Synthetic routed cycle completion']);const req=(await owner.query('SELECT id,source_media_asset_version_id FROM medialab_core.returned_quick_edit_requests')).rows[0];expect(req.source_media_asset_version_id).toBe(x.versions[0]);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_approved_source_designations')).rows[0].n).toBe(0);const corrected=await runtime.query<{add_media_asset_version:string}>('SELECT medialab_core.add_media_asset_version($1,$2,$3,$4,$5,$6,$7,$8,$9)',[t,`corrected-${crypto.randomUUID()}`,x.originals[0].assetId,'QUICK_EDIT_CORRECTION','corrected.jpg',1500,'image/jpeg',digest(crypto.randomUUID()),SOURCE]);await fail(runtime.query('SELECT medialab_core.associate_quick_edit_corrected_version($1,$2,$3,$4,$5)',[t,`bad-link-${crypto.randomUUID()}`,req.id,corrected.rows[0].add_media_asset_version,'No lineage yet']),/lacks immutable/);await runtime.query('SELECT medialab_core.record_media_lineage($1,$2,$3,$4,$5,$6)',[t,`lineage-${crypto.randomUUID()}`,x.versions[0],corrected.rows[0].add_media_asset_version,'EDITOR_RETURN_TO_CORRECTED_VERSION','Synthetic Quick Edit lineage']);await runtime.query('SELECT medialab_core.associate_quick_edit_corrected_version($1,$2,$3,$4,$5)',[t,`link-${crypto.randomUUID()}`,req.id,corrected.rows[0].add_media_asset_version,'Synthetic corrected version association']);expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_approved_source_designations')).rows[0].n).toBe(0);const r2=await review(t,x.handoffId,[corrected.rows[0].add_media_asset_version],2);await runtime.query('SELECT medialab_core.link_returned_review_successor($1,$2,$3,$4,$5)',[t,`successor-${crypto.randomUUID()}`,r1.batchId,r2.batchId,'Synthetic successor cycle']);await decide(t,r2.items[0],'ACCEPT');expect((await owner.query('SELECT version_id FROM medialab_core.media_approved_source_designations')).rows[0].version_id).toBe(corrected.rows[0].add_media_asset_version);});

  it('Needs Review uses an isolated successor cycle, stays unresolved, creates no final source, and preserves history',async()=>{
    const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,1),predecessor=await review(t,x.handoffId,x.versions);
    await decide(t,predecessor.items[0],'QUICK_EDIT',0,'Correct vertical alignment only');
    await runtime.query('SELECT medialab_core.complete_returned_review_batch($1,$2,$3,$4,$5)',[t,`complete-${crypto.randomUUID()}`,predecessor.batchId,2,'Synthetic routed cycle completion']);
    const request=(await owner.query('SELECT id,source_media_asset_version_id FROM medialab_core.returned_quick_edit_requests')).rows[0];
    const corrected=await runtime.query<{add_media_asset_version:string}>('SELECT medialab_core.add_media_asset_version($1,$2,$3,$4,$5,$6,$7,$8,$9)',[t,`needs-review-corrected-${crypto.randomUUID()}`,x.originals[0].assetId,'QUICK_EDIT_CORRECTION','needs-review-corrected.jpg',1500,'image/jpeg',digest(crypto.randomUUID()),SOURCE]);
    await runtime.query('SELECT medialab_core.record_media_lineage($1,$2,$3,$4,$5,$6)',[t,`needs-review-lineage-${crypto.randomUUID()}`,request.source_media_asset_version_id,corrected.rows[0].add_media_asset_version,'EDITOR_RETURN_TO_CORRECTED_VERSION','Synthetic Needs Review lineage']);
    await runtime.query('SELECT medialab_core.associate_quick_edit_corrected_version($1,$2,$3,$4,$5)',[t,`needs-review-link-${crypto.randomUUID()}`,request.id,corrected.rows[0].add_media_asset_version,'Synthetic Needs Review association']);
    const successor=await review(t,x.handoffId,[corrected.rows[0].add_media_asset_version],2);
    await runtime.query('SELECT medialab_core.link_returned_review_successor($1,$2,$3,$4,$5)',[t,`needs-review-successor-${crypto.randomUUID()}`,predecessor.batchId,successor.batchId,'Explicit Needs Review successor cycle']);
    const current=(await owner.query('SELECT current_state,resolved_count,unresolved_count,final_source_count FROM medialab_core.returned_review_batch_current WHERE review_batch_id=$1',[successor.batchId])).rows[0];
    expect(current).toMatchObject({current_state:'SEALED',resolved_count:0,unresolved_count:1,final_source_count:0});
    expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_approved_source_designations')).rows[0].n).toBe(0);
    expect((await owner.query('SELECT count(*)::int n FROM medialab_core.returned_review_successor_links WHERE predecessor_review_batch_id=$1 AND successor_review_batch_id=$2',[predecessor.batchId,successor.batchId])).rows[0].n).toBe(1);
    expect((await owner.query('SELECT count(*)::int n FROM medialab_core.media_asset_lineage WHERE source_version_id=$1 AND target_version_id=$2',[request.source_media_asset_version_id,corrected.rows[0].add_media_asset_version])).rows[0].n).toBe(1);
  });

  it('SKIP_QUICK_EDIT stays unresolved and actor idempotency, stale generations, and tenant scope fail atomically',async()=>{const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,1),rv=await review(t,x.handoffId,x.versions);const key=`idem-${crypto.randomUUID()}`;const a=await decide(t,rv.items[0],'SKIP_QUICK_EDIT',0,null,key);const b=await decide(t,rv.items[0],'SKIP_QUICK_EDIT',0,null,key);expect(b.rows).toEqual(a.rows);await fail(decide(t,rv.items[0],'ACCEPT',0,null,key),/Idempotency key.*different request/i);await fail(runtime.query('SELECT medialab_core.complete_returned_review_batch($1,$2,$3,$4,$5)',[t,`incomplete-${crypto.randomUUID()}`,rv.batchId,2,'Should remain unresolved']),/explicit resolving/);expect((await owner.query('SELECT current_route_state FROM medialab_core.returned_review_item_current WHERE review_item_id=$1',[rv.items[0]])).rows[0].current_route_state).toBe('SKIP_QUICK_EDIT_UNRESOLVED');await fail(runtime.query('SELECT medialab_core.admit_returned_review_item($1,$2,$3,$4,$5,$6::jsonb)',[t,`sealed-${crypto.randomUUID()}`,rv.batchId,x.originals[0].originalId,2,'{}']),/accepted returned-media|sealed|lineage/);});

  it('rejects unsafe evidence and direct mutation while PUBLIC has zero packet authority and no side effects occur',async()=>{const t=await session(),j=await job(t),x=await handoffWithReturns(t,j,1);await fail(runtime.query('SELECT medialab_core.create_returned_review_batch($1,$2,$3,$4,$5,$6::jsonb)',[t,`unsafe-${crypto.randomUUID()}`,x.handoffId,1,'Unsafe token https://example.invalid','{"provider_payload":{"base64":"AA=="}}']),/prohibited|Bounded/);const rv=await review(t,x.handoffId,x.versions);await fail(runtime.query('INSERT INTO medialab_core.returned_review_decisions(id,review_item_id,review_batch_id,organization_id,job_id,reviewed_media_asset_version_id,disposition,reason,decided_by_identity_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[crypto.randomUUID(),rv.items[0],rv.batchId,ORGANIZATION_FIXTURE.id,j.jobId,x.versions[0],'REJECT_REVISION','Direct DML',ACTOR]),/permission denied/);await fail(owner.query('DELETE FROM medialab_core.returned_review_items'),/immutable append-only/);const p=await owner.query(`SELECT count(*) FILTER (WHERE has_function_privilege('public',p.oid,'EXECUTE'))::int f FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='medialab_core' AND (p.proname LIKE '%returned_review%' OR p.proname LIKE '%quick_edit_corrected%')`);expect(p.rows[0].f).toBe(0);const non=await owner.query(`SELECT (SELECT count(*)::int FROM medialab_core.media_storage_objects) storage,(SELECT count(*)::int FROM medialab_core.media_transfer_events) transfers,(SELECT count(*)::int FROM medialab_core.media_operations) operations`);expect(non.rows[0]).toEqual({storage:0,transfers:0,operations:0});});
});
